//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazing.Mvvm.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazing.Mvvm.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes ending with &apos;ViewModel&apos; should inherit from one of the Blazing.Mvvm base classes to ensure proper MVVM pattern implementation and lifecycle management..
        /// </summary>
        internal static string BLAZMVVM0001_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; should inherit from ViewModelBase, RecipientViewModelBase, or ValidatorViewModelBase.
        /// </summary>
        internal static string BLAZMVVM0001_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel should inherit from ViewModelBase.
        /// </summary>
        internal static string BLAZMVVM0001_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModels that inherit from ViewModelBase must be decorated with the [ViewModelDefinition] attribute to ensure proper dependency injection registration and service lifetime configuration..
        /// </summary>
        internal static string BLAZMVVM0002_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be decorated with [ViewModelDefinition] attribute for dependency injection registration.
        /// </summary>
        internal static string BLAZMVVM0002_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel must have ViewModelDefinition attribute.
        /// </summary>
        internal static string BLAZMVVM0002_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor components that have a ViewModel property should inherit from MvvmComponentBase&lt;TViewModel&gt; to ensure automatic ViewModel injection, proper lifecycle management, and state synchronization..
        /// </summary>
        internal static string BLAZMVVM0003_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component &apos;{0}&apos; with ViewModel property should inherit from MvvmComponentBase&lt;TViewModel&gt;.
        /// </summary>
        internal static string BLAZMVVM0003_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component should inherit from MvvmComponentBase.
        /// </summary>
        internal static string BLAZMVVM0003_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties decorated with [ViewParameter] attribute must have corresponding [Parameter] properties in the associated component to maintain proper data flow between Views and ViewModels..
        /// </summary>
        internal static string BLAZMVVM0004_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; with [ViewParameter] attribute must have a matching [Parameter] property in the associated component.
        /// </summary>
        internal static string BLAZMVVM0004_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewParameter must have matching Component parameter.
        /// </summary>
        internal static string BLAZMVVM0004_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation calls must reference ViewModels that are properly registered with [ViewModelDefinition] and have associated routable components to prevent runtime navigation failures..
        /// </summary>
        internal static string BLAZMVVM0005_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0005_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigateTo&lt;{0}&gt;() references a type that is not registered with [ViewModelDefinition] or has no associated route.
        /// </summary>
        internal static string BLAZMVVM0005_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation target must be a registered ViewModel.
        /// </summary>
        internal static string BLAZMVVM0005_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [ViewModelKey] attribute value must exactly match the name of a registered ViewModel type to ensure proper ViewModel resolution at runtime..
        /// </summary>
        internal static string BLAZMVVM0006_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0006_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ViewModelKey] attribute value &apos;{0}&apos; does not match any registered ViewModel type name.
        /// </summary>
        internal static string BLAZMVVM0006_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0006_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModelKey must match registered ViewModel name.
        /// </summary>
        internal static string BLAZMVVM0006_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business logic in component lifecycle methods should be moved to corresponding ViewModel lifecycle methods to maintain proper separation of concerns in MVVM architecture..
        /// </summary>
        internal static string BLAZMVVM0007_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0007_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component &apos;{0}&apos; overrides lifecycle method &apos;{1}&apos; - consider moving logic to ViewModel lifecycle methods.
        /// </summary>
        internal static string BLAZMVVM0007_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0007_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider overriding lifecycle methods in ViewModel.
        /// </summary>
        internal static string BLAZMVVM0007_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties with backing fields and manual SetProperty calls should use the [ObservableProperty] attribute from CommunityToolkit.Mvvm to reduce boilerplate code and improve maintainability..
        /// </summary>
        internal static string BLAZMVVM0008_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0008_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; with backing field should use [ObservableProperty] attribute instead of manual SetProperty calls.
        /// </summary>
        internal static string BLAZMVVM0008_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0008_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property should use ObservableProperty attribute.
        /// </summary>
        internal static string BLAZMVVM0008_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor parameters in ViewModels should reference services that are registered in the dependency injection container to prevent runtime resolution failures..
        /// </summary>
        internal static string BLAZMVVM0009_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0009_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor parameter &apos;{0}&apos; of type &apos;{1}&apos; may not be registered in the dependency injection container.
        /// </summary>
        internal static string BLAZMVVM0009_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0009_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service may not be registered in DI container.
        /// </summary>
        internal static string BLAZMVVM0009_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor page components with @page directive should have an associated ViewModel to maintain consistent MVVM architecture across routable pages..
        /// </summary>
        internal static string BLAZMVVM0010_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page component &apos;{0}&apos; with @page directive should have an associated ViewModel.
        /// </summary>
        internal static string BLAZMVVM0010_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page should have associated ViewModel.
        /// </summary>
        internal static string BLAZMVVM0010_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MvvmNavLink components must reference ViewModels that are properly registered with [ViewModelDefinition] and have associated routable components for type-safe navigation..
        /// </summary>
        internal static string BLAZMVVM0011_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0011_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MvvmNavLink references ViewModel &apos;{0}&apos; that is not registered or has no associated route.
        /// </summary>
        internal static string BLAZMVVM0011_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MvvmNavLink must reference valid ViewModel.
        /// </summary>
        internal static string BLAZMVVM0011_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0011_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods called directly from Views should be converted to commands using the [RelayCommand] attribute to follow MVVM command pattern and enable features like CanExecute logic..
        /// </summary>
        internal static string BLAZMVVM0012_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0012_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; called from View should be converted to a command using [RelayCommand] attribute.
        /// </summary>
        internal static string BLAZMVVM0012_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0012_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be converted to RelayCommand.
        /// </summary>
        internal static string BLAZMVVM0012_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0012_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components with ViewModels that implement IDisposable or use scoped services should inherit from MvvmOwningComponentBase&lt;TViewModel&gt; to ensure proper service scope and disposal management..
        /// </summary>
        internal static string BLAZMVVM0013_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0013_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component &apos;{0}&apos; with ViewModel &apos;{1}&apos; that implements IDisposable should inherit from MvvmOwningComponentBase&lt;TViewModel&gt;.
        /// </summary>
        internal static string BLAZMVVM0013_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0013_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using MvvmOwningComponentBase for scoped services.
        /// </summary>
        internal static string BLAZMVVM0013_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0013_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual StateHasChanged calls are unnecessary when using ObservableProperty attributes, as the MVVM framework automatically triggers UI updates when observable properties change..
        /// </summary>
        internal static string BLAZMVVM0014_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0014_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateHasChanged call after &apos;{0}&apos; is unnecessary when using ObservableProperty - automatic UI updates are handled by the framework.
        /// </summary>
        internal static string BLAZMVVM0014_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0014_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary StateHasChanged call detected.
        /// </summary>
        internal static string BLAZMVVM0014_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0014_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModels that use disposable resources such as subscriptions, timers, or unmanaged resources should implement IDisposable to ensure proper cleanup and prevent memory leaks..
        /// </summary>
        internal static string BLAZMVVM0015_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0015_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel &apos;{0}&apos; uses disposable resources but does not implement IDisposable pattern.
        /// </summary>
        internal static string BLAZMVVM0015_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0015_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel should implement IDisposable.
        /// </summary>
        internal static string BLAZMVVM0015_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0015_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger registrations should be unregistered when the ViewModel is disposed to prevent memory leaks. Consider using RecipientViewModelBase which handles registration lifetime automatically..
        /// </summary>
        internal static string BLAZMVVM0016_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0016_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger.Register call in &apos;{0}&apos; is not unregistered - consider calling Unregister in Dispose or use RecipientViewModelBase.
        /// </summary>
        internal static string BLAZMVVM0016_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0016_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger registration may cause memory leak.
        /// </summary>
        internal static string BLAZMVVM0016_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0016_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous command methods should return Task and use AsyncRelayCommand instead of async void to enable proper exception handling, cancellation support, and execution state tracking..
        /// </summary>
        internal static string BLAZMVVM0017_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0017_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async method &apos;{0}&apos; with [RelayCommand] should use AsyncRelayCommand instead of async void to properly handle exceptions.
        /// </summary>
        internal static string BLAZMVVM0017_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0017_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async method should use AsyncRelayCommand.
        /// </summary>
        internal static string BLAZMVVM0017_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0017_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When one property change affects another computed property, use the [NotifyPropertyChangedFor] attribute to automatically notify dependents instead of manually calling OnPropertyChanged..
        /// </summary>
        internal static string BLAZMVVM0018_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0018_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is referenced in &apos;{1}&apos; - consider adding [NotifyPropertyChangedFor(nameof({1}))] to &apos;{0}&apos; for automatic notification.
        /// </summary>
        internal static string BLAZMVVM0018_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0018_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using NotifyPropertyChangedFor attribute.
        /// </summary>
        internal static string BLAZMVVM0018_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0018_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency injection services should be injected using [Inject] attribute in ViewModels rather than [CascadingParameter] to maintain clear separation between component hierarchy state and service dependencies..
        /// </summary>
        internal static string BLAZMVVM0019_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0019_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; with [CascadingParameter] should use [Inject] instead for dependency injection services.
        /// </summary>
        internal static string BLAZMVVM0019_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0019_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Inject over CascadingParameter for services.
        /// </summary>
        internal static string BLAZMVVM0019_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0019_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route parameters defined in @page directive should have corresponding [ViewParameter] properties in the ViewModel to ensure proper parameter binding and maintain MVVM data flow..
        /// </summary>
        internal static string BLAZMVVM0020_Description {
            get {
                return ResourceManager.GetString("BLAZMVVM0020_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route parameter &apos;{0}&apos; in @page directive should have matching [ViewParameter] property in ViewModel &apos;{1}&apos;.
        /// </summary>
        internal static string BLAZMVVM0020_MessageFormat {
            get {
                return ResourceManager.GetString("BLAZMVVM0020_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route parameter should be bound to ViewModel.
        /// </summary>
        internal static string BLAZMVVM0020_Title {
            get {
                return ResourceManager.GetString("BLAZMVVM0020_Title", resourceCulture);
            }
        }
    }
}
